In [2]:
# 1. load the text data from some source(plain text, pdf, html e.g)

with open('train.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print(text[1000:1500])
len(text)

ional response and perception consciously
practiced by the victims of white supremacy (racism)- with the objective
· of eradicating racism at the global level. Functionally speaking, for the
of white supremacy, this means to act in a self/group-respecting
supporting manner in all areas of people activity, despite the specific
conditions of racist domination and oppression. Submission to and
·C<J<>pe~:aticm with victimization and oppression are signs of individual or
mental illness or self-negati


468110

In [3]:
# 2. get all unique chars in our text data

char = sorted(list(set(text[:]))) # a list of a set of char in the text file --> sorted
vocab_size = len(char)
print(vocab_size)
print(''.join(char))
type(char)

96

 !"#$%&'()*,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_abcdefghijklmnopqrstuvwxyz{}~£«­·•


list

In [4]:
l = [str(i) for i in range(1, 6)]
''.join(l)

'12345'

In [5]:
# 3. use dicts to map each unique characters to integer representation

basil = {ch:i for i, ch in enumerate(char)}
lisab = {i:ch for i, ch in enumerate(char)}

enc = lambda s: [basil[c] for c in s]
dec = lambda l: ''.join([lisab[i] for i in l])

print(enc('hey lennox'))
print(enc('lennox likes machine learning'.upper()))
print(dec(enc('lennox likes machine learning')))

[69, 66, 86, 1, 73, 66, 75, 75, 76, 85]
[43, 36, 45, 45, 46, 55, 1, 43, 40, 42, 36, 50, 1, 44, 32, 34, 39, 40, 45, 36, 1, 43, 36, 32, 49, 45, 40, 45, 38]
lennox likes machine learning


In [6]:
# 4. create tensor repr for our input text data using pytorch

import torch

data = torch.tensor(enc(text), dtype=torch.long)
print(data.shape, data.type())

torch.Size([468110]) torch.LongTensor


In [7]:
print(f'{data[:100]}')

tensor([32,  1, 64, 82, 73, 81, 82, 79, 66,  1, 64, 62, 75,  1, 63, 66,  1, 73,
        70, 72, 66, 75, 66, 65,  1, 81, 76,  1, 62,  1, 78, 82, 70, 73, 81,  1,
        76, 67,  1, 70, 75, 81, 79, 70, 64, 62, 81, 66,  1, 68, 66, 76, 74, 66,
        81, 79, 70, 64, 62, 73,  1, 65, 66, 80, 70, 68, 75,  1, 70, 75,  0, 84,
        69, 70, 64, 69,  1, 62, 73, 73,  1, 76, 67,  1, 81, 69, 66,  1, 74, 62,
        75, 86,  1, 64, 76, 73, 76, 79, 66, 65])


In [8]:
# 5. split the data into train and test sets

n = int(0.9*len(data))
train = data[:n]
eval = data[n:]

In [9]:
block = 8
train[:block+1]

tensor([32,  1, 64, 82, 73, 81, 82, 79, 66])

In [10]:
x = train[:block]
y = train[1:block +1]

for t in range(block):
    context = x[:t+1]
    target = y[t]
    print(f'when the input is {context}, the target is {target}')

when the input is tensor([32]), the target is 1
when the input is tensor([32,  1]), the target is 64
when the input is tensor([32,  1, 64]), the target is 82
when the input is tensor([32,  1, 64, 82]), the target is 73
when the input is tensor([32,  1, 64, 82, 73]), the target is 81
when the input is tensor([32,  1, 64, 82, 73, 81]), the target is 82
when the input is tensor([32,  1, 64, 82, 73, 81, 82]), the target is 79
when the input is tensor([32,  1, 64, 82, 73, 81, 82, 79]), the target is 66


In [11]:
torch.manual_seed(42)

batch = 4
block = 8

def get_batch(split):
    data = train if split == 'train' else eval
    ix = torch.randint(len(data) -block,(batch,))
    x = torch.stack([data[i:i+block] for i in ix])
    y = torch.stack([data[i+1:i+block+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)
print('-------')
for b in range(batch):
    for t in range(block):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f'when input is {context.tolist()} the target is {target}')


inputs:
torch.Size([4, 8])
tensor([[ 0, 64, 66, 75, 81, 82, 79, 86],
        [64, 69, 70, 66, 83, 66, 65,  1],
        [86,  1, 81, 69, 66,  1, 77, 69],
        [79, 62, 75, 80, 73, 62, 81, 66]])
targets:
torch.Size([4, 8])
tensor([[64, 66, 75, 81, 82, 79, 86, 14],
        [69, 70, 66, 83, 66, 65,  1, 63],
        [ 1, 81, 69, 66,  1, 77, 69, 79],
        [62, 75, 80, 73, 62, 81, 66, 65]])
-------
when input is [0] the target is 64
when input is [0, 64] the target is 66
when input is [0, 64, 66] the target is 75
when input is [0, 64, 66, 75] the target is 81
when input is [0, 64, 66, 75, 81] the target is 82
when input is [0, 64, 66, 75, 81, 82] the target is 79
when input is [0, 64, 66, 75, 81, 82, 79] the target is 86
when input is [0, 64, 66, 75, 81, 82, 79, 86] the target is 14
when input is [64] the target is 69
when input is [64, 69] the target is 70
when input is [64, 69, 70] the target is 66
when input is [64, 69, 70, 66] the target is 83
when input is [64, 69, 70, 66, 83] the 

In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(43)

# create a neural network by subclassing nn.Module which is the base class for building neural networks with pytorch
class BigLangModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    # implementing a loss function in pytorch

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None

        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=1)

            idx_next  = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx
    
    
n = BigLangModel(vocab_size)
logits, loss = n(xb, yb)
print(logits.shape)
print(loss)

print(dec(n.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))
    

torch.Size([32, 96])
tensor(4.8323, grad_fn=<NllLossBackward0>)

)vm7XKw\h?OT8=G:U;UNUcGg?Ff6«9mm£>7<$~WE5i*\Jx]?-x«cQw;p#6)z #u.Z/'"
sJ[=W;rM67~2£GXhO«G6rM3M:9-.u]K


In [13]:
# create a pytorch optimzer

opt = torch.optim.AdamW(n.parameters())

batch = 0
for steps in range(100):
    xb, yb = get_batch('train')

    logits, loss = n(xb, yb)
    opt.zero_grad(set_to_none=True)
    loss.backward()
    opt.step()

print(loss.items())

/home/lennox/ml_projects/ml/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


RuntimeError: stack expects a non-empty TensorList